#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

case "$1" in
  start)
    stat_busy "Automatically logging in"
    dtach -n /var/run/autologin.dtach su -c 'sh -l -c startx' robin
    if [ $? -gt 0 ]; then
      stat_fail
    else
      stat_done
    fi
    ;;
 stop)
    ;;
  restart)
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
exit 0
