#!/bin/zsh

run() {
  ./Build/Debug/Evernote.app/Contents/MacOS/Evernote 2>&1 | golorize \
      -conf ~/.golorize/en-mac-log.json
  return $?
}

clean() {
  xctool -project "EverNote.xcodeproj" -scheme "Evernote-Homebrew" clean
  rm -Rf ./Build/Debug/Evernote.app
  return $?
}

buildHomeBrew() {
  xctool -project "EverNote.xcodeproj" -scheme "Evernote-Homebrew"
  return $?
}

if [[ "$1" == "build" ]]; then
  buildHomeBrew &&
  run
elif [[ "$1" == "run" ]]; then
  run
elif [[ "$1" == "clean" ]]; then
  clean
elif [[ "$1" == "onlybuild" ]]; then
  buildHomeBrew
fi
