#!/bin/bash
for file in ./*.png ; do 
    thumbnail="${file%.png}-thumb.png"
	convert "${file}" -resize 500x $thumbnail
	composite -compose atop -gravity SouthWest ${0%/*}/garoth-impose-bottom.png $thumbnail $thumbnail
	composite -compose atop -gravity NorthEast ${0%/*}/garoth-impose-top.png $thumbnail $thumbnail
	echo "Composing image on top of $thumbnail";
done
