#!/bin/bash
# Finds available wireless networks on given interface
# Usage: wl-find-networks wlan0

export SPACE_EVERY=2 # put a space every this number of lines

check-root.sh
if [ $? -eq 1 ]; then
        echo "Must be root to run this script."
        exit 1
fi

check-interface-up.sh $1
if [ $? -eq 1 ]; then
        echo "Interface must be up in order to scan on it"
        exit 1
fi

iwlist $1 scan | egrep "Encrypt|ESSID" | sed "s/^ *//" > /tmp/outp

echo "Available Networks"
echo "=================="

export COUNT=$SPACE_EVERY
cat /tmp/outp | while read line; do
        if [ $COUNT -ge $SPACE_EVERY ]; then
                COUNT=0
                echo ""
        fi
        COUNT=$(perl -e "print $COUNT + 1")

        echo $line
done
