#!/bin/bash

export SPACE_EVERY=2 # put a space every this number of lines

iwlist wlan0 scan | egrep "Encrypt|ESSID" | sed "s/^ *//" > /tmp/outp

echo "Available Networks"
echo "=================="
echo ""

export COUNT=0
cat /tmp/outp | while read line; do
        COUNT=$(perl -e "print $COUNT + 1")
        echo $line

        if [ $COUNT -ge $SPACE_EVERY ]; then
                COUNT=0
                echo ""
        fi
done
